# Generated by Django 5.0.3 on 2024-03-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tp_imovel_tipoimovel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
